name: CI

"on": [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # full history for metadata
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Python install
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install "ltd-conveyor<2.0.0"

      - name: Build
        run: |
          make html

      - name: Upload
        run: |
          ltd upload --gh --dir _build/html --product testn-088
